name: Flask Docker CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build and run Docker Compose
      run: |
        docker-compose up -d --build
        sleep 10  # даємо час на запуск

    - name: Check Flask is running
      run: |
        curl --fail http://localhost:5000 || exit 1
