name: Flask Docker CI

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      docker:
        image: docker:20.10.7
        options: --privileged

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: pip install mysql-connector-python flask

    - name: Build and run containers
      run: docker compose up -d

    - name: Wait for MySQL to be healthy
      run: |
        for i in {1..10}; do
          if docker inspect --format='{{.State.Health.Status}}' flask_docker_app-mysql_db-1 | grep healthy; then
            echo "✅ MySQL is healthy"
            break
          fi
          echo "⏳ Waiting for MySQL..."
          sleep 3
        done

    - name: Run Flask app in background
      run: |
        python app.py &
        sleep 5

    - name: Check Flask /health endpoint
      run: |
        for i in {1..10}; do
          echo "🩺 Перевірка Flask /health ($i)"
          if curl --fail http://localhost:5000/health; then
            echo "✅ Flask відповідає!"
            exit 0
          fi
          sleep 3
        done
        echo "❌ Flask не відповідає"
        exit 1

